// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pfe_back.Data;

#nullable disable

namespace pfe_back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pfe_back.Models.Candidature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePostulation")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroEnregistrement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PosteId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.HasIndex("PosteId");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("pfe_back.Models.Commission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Commissions");
                });

            modelBuilder.Entity("pfe_back.Models.Decision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DAOId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLimite")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSignature")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbreMaxPosteCandidat")
                        .HasColumnType("int");

                    b.Property<int>("PVId")
                        .HasColumnType("int");

                    b.Property<string>("PieceJoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DAOId");

                    b.HasIndex("PVId")
                        .IsUnique();

                    b.ToTable("Decision");
                });

            modelBuilder.Entity("pfe_back.Models.Diplome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnéeObtention")
                        .HasColumnType("int");

                    b.Property<int>("CandidatId")
                        .HasColumnType("int");

                    b.Property<string>("Etablissement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intitulé")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.ToTable("Diplomes");
                });

            modelBuilder.Entity("pfe_back.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatureId")
                        .HasColumnType("int");

                    b.Property<string>("Lien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("pfe_back.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDébut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entreprise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.ToTable("Experience");
                });

            modelBuilder.Entity("pfe_back.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("pfe_back.Models.PV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommissionId")
                        .HasColumnType("int");

                    b.Property<int>("DAOId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateValidation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PieceJointe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypePosteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommissionId");

                    b.HasIndex("DAOId");

                    b.HasIndex("TypePosteId");

                    b.ToTable("PV");
                });

            modelBuilder.Entity("pfe_back.Models.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecisionId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.ToTable("Phase");
                });

            modelBuilder.Entity("pfe_back.Models.Poste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Critere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecisionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exigence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroUnique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PVId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("PVId");

                    b.ToTable("Poste");
                });

            modelBuilder.Entity("pfe_back.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("pfe_back.Models.TypePoste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypePoste");
                });

            modelBuilder.Entity("pfe_back.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UtilisateurType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator<string>("UtilisateurType").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("pfe_back.Models.Administrateur", b =>
                {
                    b.HasBaseType("pfe_back.Models.Utilisateur");

                    b.HasDiscriminator().HasValue("Administrateur");
                });

            modelBuilder.Entity("pfe_back.Models.Candidat", b =>
                {
                    b.HasBaseType("pfe_back.Models.Utilisateur");

                    b.Property<string>("AffectationActuelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Catégorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Congé")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Consentement")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateRetraite")
                        .HasColumnType("datetime2");

                    b.Property<int>("JoursAbsence")
                        .HasColumnType("int");

                    b.Property<string>("NoteTroisDernieresAnnees")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosteOccupe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sanction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Candidat");
                });

            modelBuilder.Entity("pfe_back.Models.DAO", b =>
                {
                    b.HasBaseType("pfe_back.Models.Utilisateur");

                    b.HasDiscriminator().HasValue("DAO");
                });

            modelBuilder.Entity("pfe_back.Models.MembreCommission", b =>
                {
                    b.HasBaseType("pfe_back.Models.Utilisateur");

                    b.Property<int>("CommissionId")
                        .HasColumnType("int");

                    b.HasIndex("CommissionId");

                    b.HasDiscriminator().HasValue("MembreCommission");
                });

            modelBuilder.Entity("pfe_back.Models.Candidature", b =>
                {
                    b.HasOne("pfe_back.Models.Candidat", "Candidat")
                        .WithMany("Candidatures")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pfe_back.Models.Poste", "Poste")
                        .WithMany("Candidatures")
                        .HasForeignKey("PosteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");

                    b.Navigation("Poste");
                });

            modelBuilder.Entity("pfe_back.Models.Decision", b =>
                {
                    b.HasOne("pfe_back.Models.DAO", "DAO")
                        .WithMany("Decisions")
                        .HasForeignKey("DAOId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pfe_back.Models.PV", "PV")
                        .WithOne("Decision")
                        .HasForeignKey("pfe_back.Models.Decision", "PVId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DAO");

                    b.Navigation("PV");
                });

            modelBuilder.Entity("pfe_back.Models.Diplome", b =>
                {
                    b.HasOne("pfe_back.Models.Candidat", "Candidat")
                        .WithMany("Diplomes")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");
                });

            modelBuilder.Entity("pfe_back.Models.Document", b =>
                {
                    b.HasOne("pfe_back.Models.Candidature", "Candidature")
                        .WithMany("Documents")
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("pfe_back.Models.Experience", b =>
                {
                    b.HasOne("pfe_back.Models.Candidat", "Candidat")
                        .WithMany("Experiences")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");
                });

            modelBuilder.Entity("pfe_back.Models.Notification", b =>
                {
                    b.HasOne("pfe_back.Models.Candidature", "Candidature")
                        .WithMany("Notifications")
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("pfe_back.Models.PV", b =>
                {
                    b.HasOne("pfe_back.Models.Commission", "Commission")
                        .WithMany("PVs")
                        .HasForeignKey("CommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pfe_back.Models.DAO", "DAO")
                        .WithMany("PVs")
                        .HasForeignKey("DAOId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pfe_back.Models.TypePoste", "TypePoste")
                        .WithMany("PVs")
                        .HasForeignKey("TypePosteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commission");

                    b.Navigation("DAO");

                    b.Navigation("TypePoste");
                });

            modelBuilder.Entity("pfe_back.Models.Phase", b =>
                {
                    b.HasOne("pfe_back.Models.Decision", "Decision")
                        .WithMany("Phases")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decision");
                });

            modelBuilder.Entity("pfe_back.Models.Poste", b =>
                {
                    b.HasOne("pfe_back.Models.Decision", "Decision")
                        .WithMany("Postes")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pfe_back.Models.PV", "PV")
                        .WithMany("Postes")
                        .HasForeignKey("PVId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Decision");

                    b.Navigation("PV");
                });

            modelBuilder.Entity("pfe_back.Models.Utilisateur", b =>
                {
                    b.HasOne("pfe_back.Models.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("pfe_back.Models.MembreCommission", b =>
                {
                    b.HasOne("pfe_back.Models.Commission", "Commission")
                        .WithMany("MembreCommissions")
                        .HasForeignKey("CommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commission");
                });

            modelBuilder.Entity("pfe_back.Models.Candidature", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("pfe_back.Models.Commission", b =>
                {
                    b.Navigation("MembreCommissions");

                    b.Navigation("PVs");
                });

            modelBuilder.Entity("pfe_back.Models.Decision", b =>
                {
                    b.Navigation("Phases");

                    b.Navigation("Postes");
                });

            modelBuilder.Entity("pfe_back.Models.PV", b =>
                {
                    b.Navigation("Decision")
                        .IsRequired();

                    b.Navigation("Postes");
                });

            modelBuilder.Entity("pfe_back.Models.Poste", b =>
                {
                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("pfe_back.Models.Role", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("pfe_back.Models.TypePoste", b =>
                {
                    b.Navigation("PVs");
                });

            modelBuilder.Entity("pfe_back.Models.Candidat", b =>
                {
                    b.Navigation("Candidatures");

                    b.Navigation("Diplomes");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("pfe_back.Models.DAO", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("PVs");
                });
#pragma warning restore 612, 618
        }
    }
}
